### ISSUE TITLE
support windows ag

### ISSUE THREAD

**Issue by fommil** [Wilfred/ag.el#101] opened 2015-12-03 13:15 UTC
emacs ag doesn't appear to work on windows, in the sense that the output is not parsed correctly and files are not identified. It seems that the extra command line arguments are suppressing the filename.

This is the output of a search using `ag`

```
"ag.exe" "--nocolor" "--literal" "--line-number" "--smart-case" "--nogroup" "--column" "--stats" "--" "exportedProducts" "."
552:3:  exportedProducts in Compile := Nil,
1003:38:    fullClasspath <<= concatDistinct(exportedProducts, dependencyClasspath),
1007:5:    exportedProducts <<= exportProductsTask,
1641:18:    getClasspath(exportedProducts, dep, conf, data)
51:22:        val prods = (exportedProducts in Runtime).value
235:7:  val exportedProducts = TaskKey[Classpath]("exported-products", "Build products that go on the exported classpath.", CTask)
17:15:import Keys.{ exportedProducts, loadedBuild, onLoadMessage, resolvedScoped, sbtPlugin, scalacOptions, taskDefinitionKey }
750:19:      val prod = (exportedProducts in Configurations.Runtime).value
10412:22:        val prods = (exportedProducts in Runtime).valueprods51,2438
10868:7:  val exportedProducts = TaskKey[Classpath]("exported-products", "Build products that go on the exported classpath.", CTask)exportedProducts235,25025
11228:19:      val prod = (exportedProducts in Configurations.Runtime).valueprod750,42188
12 matches
1804 files searched
4937895 bytes searched
1.039104 seconds
```

and for `projectile-ag`

```
"ag.exe" "--ignore" "TAGS" "--ignore" ".idea/" "--ignore" ".eunit/" "--ignore" ".git/" "--ignore" ".hg/" "--ignore" ".fslckout/" "--ignore" ".bzr/" "--ignore" "_darcs/" "--ignore" ".tox/" "--ignore" ".svn/" "--ignore" ".stack-work/" "--ignore" ".#*" "--ignore" "*.o" "--ignore" "*~" "--ignore" "*.bin" "--ignore" "*.bak" "--ignore" "*.obj" "--ignore" "*.map" "--ignore" "*.ico" "--ignore" "*.pif" "--ignore" "*.lnk" "--ignore" "*.a" "--ignore" "*.ln" "--ignore" "*.blg" "--ignore" "*.bbl" "--ignore" "*.dll" "--ignore" "*.drv" "--ignore" "*.vxd" "--ignore" "*.386" "--ignore" "*.elc" "--ignore" "*.lof" "--ignore" "*.glo" "--ignore" "*.idx" "--ignore" "*.lot" "--ignore" "*.fmt" "--ignore" "*.tfm" "--ignore" "*.class" "--ignore" "*.fas" "--ignore" "*.lib" "--ignore" "*.mem" "--ignore" "*.x86f" "--ignore" "*.sparcf" "--ignore" "*.dfsl" "--ignore" "*.pfsl" "--ignore" "*.d64fsl" "--ignore" "*.p64fsl" "--ignore" "*.lx64fsl" "--ignore" "*.lx32fsl" "--ignore" "*.dx64fsl" "--ignore" "*.dx32fsl" "--ignore" "*.fx64fsl" "--ignore" "*.fx32fsl" "--ignore" "*.sx64fsl" "--ignore" "*.sx32fsl" "--ignore" "*.wx64fsl" "--ignore" "*.wx32fsl" "--ignore" "*.fasl" "--ignore" "*.ufsl" "--ignore" "*.fsl" "--ignore" "*.dxl" "--ignore" "*.lo" "--ignore" "*.la" "--ignore" "*.gmo" "--ignore" "*.mo" "--ignore" "*.toc" "--ignore" "*.aux" "--ignore" "*.cp" "--ignore" "*.fn" "--ignore" "*.ky" "--ignore" "*.pg" "--ignore" "*.tp" "--ignore" "*.vr" "--ignore" "*.cps" "--ignore" "*.fns" "--ignore" "*.kys" "--ignore" "*.pgs" "--ignore" "*.tps" "--ignore" "*.vrs" "--ignore" "*.pyc" "--ignore" "*.pyo" "--ignore" "SCCS" "--ignore" "RCS" "--ignore" "CVS" "--ignore" "MCVS" "--ignore" ".svn" "--ignore" ".git" "--ignore" ".hg" "--ignore" ".bzr" "--ignore" "_MTN" "--ignore" "_darcs" "--ignore" "{arch}" "--nocolor" "--literal" "--line-number" "--smart-case" "--nogroup" "--column" "--stats" "--" "exportedProducts" "."
552:3:  exportedProducts in Compile := Nil,
1003:38:    fullClasspath <<= concatDistinct(exportedProducts, dependencyClasspath),
1007:5:    exportedProducts <<= exportProductsTask,
1641:18:    getClasspath(exportedProducts, dep, conf, data)
51:22:        val prods = (exportedProducts in Runtime).value
235:7:  val exportedProducts = TaskKey[Classpath]("exported-products", "Build products that go on the exported classpath.", CTask)
17:15:import Keys.{ exportedProducts, loadedBuild, onLoadMessage, resolvedScoped, sbtPlugin, scalacOptions, taskDefinitionKey }
750:19:      val prod = (exportedProducts in Configurations.Runtime).value
8 matches
1803 files searched
3138440 bytes searched
0.989099 seconds
```

and for raw ag on the command line

```
build.sbt
552:  exportedProducts in Compile := Nil,

main\src\main\scala\sbt\Defaults.scala
1003:    fullClasspath <<= concatDistinct(exportedProducts, dependencyClasspath),
1007:    exportedProducts <<= exportProductsTask,
1641:    getClasspath(exportedProducts, dep, conf, data)

main\src\main\scala\sbt\GlobalPlugin.scala
51:        val prods = (exportedProducts in Runtime).value

main\src\main\scala\sbt\Keys.scala
235:  val exportedProducts = TaskKey[Classpath]("exported-products", "Build products that go on the exported classpath.", CTask)

main\src\main\scala\sbt\Load.scala
17:import Keys.{ exportedProducts, loadedBuild, onLoadMessage, resolvedScoped, sbtPlugin, scalacOptions, taskDefinitionKey }
750:      val prod = (exportedProducts in Configurations.Runtime).value

TAGS
10412:        val prods = (exportedProducts in Runtime).valueprods☺51,2438
10868:  val exportedProducts = TaskKey[Classpath]("exported-products", "Build products that go on the exported classpath.", CTask)exportedProducts☺235,25025
11228:      val prod = (exportedProducts in Configurations.Runtime).valueprod☺750,42188
```

**Comment by Wilfred** [comment] 2015-12-19 17:03
Duplicate of #97.

**Closed by Wilfred** 2015-12-19 17:03 UTC
